SELECT CUSTOMER.Name, MAX(STREAM.Charge) AS Max
FROM CUSTOMER JOIN STREAM ON(CUSTOMER.CustomerId = STREAM.CustomerId)
WHERE CUSTOMER.Country = 'United States'
      AND Year(StreamDate) = 2018
GROUP BY CUSTOMER.Name 
ORDER BY Max DESC, CUSTOMER.Name ASC;
