SELECT A1.Name, A2.Name, COUNT(DISTINCT(MovieId)) AS N, COUNT(StreamId) AS M
FROM (MOVIE_ACTOR MA1 NATURAL JOIN ACTOR A1)
JOIN (MOVIE_ACTOR MA2 NATURAL JOIN ACTOR A2) USING (MovieId)
LEFT JOIN STREAM USING(MovieId)
WHERE A1.Name < A2.Name
GROUP BY A1.Name, A2.Name
HAVING M >= 40
ORDER BY M DESC, N DESC, A1.Name, A2.Name;
