SELECT COUNTRY.Name AS Nome, Label, COUNT(StreamId)
FROM GENRE JOIN REGION
NATURAL JOIN MOVIE_GENRE
JOIN COUNTRY USING (RegionId)
JOIN CUSTOMER ON (CUSTOMER.Country = COUNTRY.Name)
LEFT OUTER JOIN STREAM USING (CustomerId, MovieId)
WHERE REGION.Name = 'Other Countries'
GROUP BY Nome, Label
ORDER BY Nome, Label;
