SELECT Label, REGION.Name AS Nome, COUNT(StreamId) AS N
FROM (MOVIE
 JOIN REGION
 JOIN COUNTRY USING(RegionId)
 JOIN CUSTOMER ON(COUNTRY.Name = CUSTOMER.Country))
 LEFT JOIN STREAM USING(MovieId, CustomerId)
 JOIN MOVIE_GENRE USING(MovieId)
 JOIN GENRE USING(GenreId)
GROUP BY Label, Nome
ORDER BY Label ASC, Nome ASC;
