SELECT A1.Name AS Nome1, A2.Name AS Nome2, COUNT(MovieId) AS N
FROM (MOVIE_ACTOR MA1
 JOIN ACTOR A1 USING(ActorId))
 JOIN (MOVIE_ACTOR MA2 JOIN ACTOR A2 USING(ActorId)) USING (MovieId)
WHERE A1.Name < A2.Name
GROUP BY A1.Name, A2.Name
HAVING N >= 4
ORDER BY N DESC, A1.Name ASC, A2.Name ASC;

