SELECT Label, REGION.Name, COUNT(StreamId) AS N
FROM
 (REGION JOIN GENRE)
 LEFT OUTER JOIN
 (
  CUSTOMER
   NATURAL JOIN STREAM
   NATURAL JOIN MOVIE_GENRE
   JOIN COUNTRY ON(CUSTOMER.Country = COUNTRY.Name)
 )
 USING(RegionId, GenreId)
GROUP BY Label, REGION.Name
ORDER BY Label, REGION.Name;
