DELETE FROM MOVIE_ACTOR
WHERE 
 MovieId IN(
  SELECT MovieId FROM MOVIE_GENRE
  JOIN GENRE ON(MOVIE_GENRE.GenreId = GENRE.GenreId)
  WHERE Label = 'Action'
)

AND ActorId IN(
  SELECT ActorId FROM ACTOR
  WHERE Name = 'Tom Cruise'
);
 
 

