UPDATE STREAM
JOIN MOVIE USING(MovieId)
SET Charge = Charge + 1.5
WHERE Duration >= 180 
 AND CustomerId IN(
  SELECT CustomerId FROM CUSTOMER
  JOIN COUNTRY ON(CUSTOMER.Country = COUNTRY.NAME)
  JOIN REGION USING(RegionId)
  WHERE REGION.Name = 'Europe'
);

