SELECT Name AS Nome, COUNT(MovieId) AS N
FROM MOVIE_ACTOR
JOIN ACTOR USING(ActorId)
WHERE 
 MovieId IN(
  SELECT MovieId FROM MOVIE_ACTOR
  JOIN MOVIE USING(MovieId)
)
GROUP BY ACTOR.Name
HAVING N >= 15
ORDER BY N DESC, Nome ASC;
