DROP VIEW IF EXISTS STREAM_COUNT_BY_COUNTRY;

CREATE VIEW STREAM_COUNT_BY_COUNTRY(Country, StreamCount)
AS (
 SELECT COUNTRY.Name AS Nomes, COUNT(STREAM.StreamId)
 FROM COUNTRY
 JOIN CUSTOMER ON(CUSTOMER.Country = COUNTRY.Name)
 LEFT JOIN STREAM ON(STREAM.CustomerId = CUSTOMER.CustomerId)
 GROUP BY Nomes
);

SELECT * FROM STREAM_COUNT_BY_COUNTRY ORDER BY StreamCount DESC, Country;


