DROP VIEW DEPARTMENT_STAFF;

CREATE VIEW DEPARTMENT_STAFF(DName, SName, Job)
AS (
 SELECT DEPARTMENT.Name AS DName, STAFF.Name AS SName, STAFF.Job AS Job
 FROM DEPARTMENT
 JOIN STAFF 
 WHERE StaffId = Manager OR Manager = Supervisor
);

SELECT * FROM DEPARTMENT_STAFF ORDER BY DName, Job, SName;
